// Mock data for the standalone demo — no auth, no database
export const DEMO_PROFILE = {
  id: 'demo-user-001',
  full_name: 'Ama Serwaa',
  username: 'amaserwaa',
  bio: 'Content creator & brand storyteller based in Accra. Specializing in lifestyle, fashion, and tech reviews across TikTok, Instagram & YouTube.',
  profile_photo_url: null,
  instagram_handle: 'amaserwaa',
  tiktok_handle: 'amaserwaa',
  twitter_handle: 'amaserwaa',
  email: 'ama@example.com',
  is_onboarded: true,
  paystack_subaccount_code: 'ACCT_demo',
}

export const DEMO_PACKAGES = [
  {
    id: 'pkg-001',
    influencer_id: 'demo-user-001',
    title: '1x TikTok Dedicated Video',
    description: 'A 30–60 second dedicated TikTok video featuring your product or service. Includes concept planning, filming, editing, and one round of revisions.',
    price: 50000, // 500.00 GHS in pesewas
    delivery_days: 3,
    is_active: true,
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'pkg-002',
    influencer_id: 'demo-user-001',
    title: 'Instagram Story Bundle (5 Slides)',
    description: 'Five Instagram story slides with swipe-up/link sticker. Includes unboxing, product showcase, and call-to-action. Ideal for product launches.',
    price: 30000, // 300.00 GHS
    delivery_days: 2,
    is_active: true,
    created_at: '2026-02-15T14:00:00Z',
  },
  {
    id: 'pkg-003',
    influencer_id: 'demo-user-001',
    title: 'Full Campaign Package',
    description: 'Complete multi-platform campaign: 1 TikTok video + 1 Instagram Reel + 5 Story slides + 1 Twitter/X post. Includes campaign brief consultation and analytics report.',
    price: 150000, // 1,500.00 GHS
    delivery_days: 7,
    is_active: true,
    created_at: '2026-03-01T09:00:00Z',
  },
]

export const DEMO_ORDERS = [
  {
    id: 'order-001',
    reference: 'REF8A3B2C01',
    paystack_reference: 'REF8A3B2C01',
    package_id: 'pkg-001',
    influencer_id: 'demo-user-001',
    client_name: 'Kwame Asante',
    client_business_name: 'Kwame Asante',
    client_email: 'kwame@brandx.com',
    product_description: 'We need a TikTok video showcasing our new wireless earbuds. Target audience is Gen Z in Ghana. Please highlight: sound quality, battery life, and the charging case. Use trending audio if possible. Brand assets attached.',
    amount: 50000,
    platform_fee: 3000,
    influencer_amount: 47000,
    payment_status: 'paid',
    order_status: 'in_progress',
    brief_image_urls: [],
    delivery_type: 'digital',
    delivery_address: null,
    on_premise_date: null,
    on_premise_location: null,
    shipment_status: 'not_applicable',
    created_at: '2026-03-20T14:30:00Z',
    packages: { title: '1x TikTok Dedicated Video' },
  },
  {
    id: 'order-002',
    reference: 'REF5D9F1A72',
    paystack_reference: 'REF5D9F1A72',
    package_id: 'pkg-003',
    influencer_id: 'demo-user-001',
    client_name: 'Efua Mensah',
    client_business_name: 'GlowUp Cosmetics',
    client_email: 'efua@glowup.gh',
    product_description: 'Full campaign for our new skincare line launching next month. We want vibrant, authentic content that shows the products in everyday use. Please include before/after shots if possible. We\'ll ship the products to you.',
    amount: 150000,
    platform_fee: 9000,
    influencer_amount: 141000,
    payment_status: 'paid',
    order_status: 'new',
    brief_image_urls: [],
    delivery_type: 'physical',
    delivery_address: {
      street: '14 Oxford Street',
      city: 'Osu, Accra',
      region: 'Greater Accra',
      zip: '',
      country: 'Ghana',
      notes: 'Call on arrival — gate is usually locked',
    },
    on_premise_date: null,
    on_premise_location: null,
    shipment_status: 'pending',
    created_at: '2026-03-22T09:15:00Z',
    packages: { title: 'Full Campaign Package' },
  },
  {
    id: 'order-003',
    reference: 'REFC7E24B93',
    paystack_reference: 'REFC7E24B93',
    package_id: 'pkg-002',
    influencer_id: 'demo-user-001',
    client_name: 'Yaw Boateng',
    client_business_name: 'FreshBite Restaurant',
    client_email: 'yaw@freshbite.com',
    product_description: 'Instagram story slides for our weekend jollof rice special. Show the food being prepared and served. Mention our location in East Legon and the 20% discount code FRESH20.',
    amount: 30000,
    platform_fee: 1800,
    influencer_amount: 28200,
    payment_status: 'paid',
    order_status: 'completed',
    brief_image_urls: [],
    delivery_type: 'digital',
    delivery_address: null,
    on_premise_date: null,
    on_premise_location: null,
    shipment_status: 'not_applicable',
    created_at: '2026-03-10T16:45:00Z',
    packages: { title: 'Instagram Story Bundle (5 Slides)' },
  },
  {
    id: 'order-004',
    reference: 'REF2B8D5E04',
    paystack_reference: 'REF2B8D5E04',
    package_id: 'pkg-001',
    influencer_id: 'demo-user-001',
    client_name: 'Adwoa Frimpong',
    client_business_name: 'TechHub Ghana',
    client_email: 'adwoa@techhub.gh',
    product_description: 'TikTok video reviewing our new co-working space. Show the workspace, meeting rooms, high-speed internet, and the rooftop lounge. Mention the first-month-free promo for new members.',
    amount: 50000,
    platform_fee: 3000,
    influencer_amount: 47000,
    payment_status: 'paid',
    order_status: 'completed',
    brief_image_urls: [],
    delivery_type: 'digital',
    delivery_address: null,
    on_premise_date: null,
    on_premise_location: null,
    shipment_status: 'not_applicable',
    created_at: '2026-02-28T11:20:00Z',
    packages: { title: '1x TikTok Dedicated Video' },
  },
]

export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'new_order',
    title: 'New Booking!',
    message: 'Efua Mensah just booked your Full Campaign Package. Tap to view the order details.',
    link: '/demo/orders/order-002',
    is_read: false,
    created_at: '2026-03-22T09:15:00Z',
  },
  {
    id: 'notif-002',
    type: 'order_completed',
    title: 'Order Completed',
    message: 'You marked Yaw Boateng\'s order as completed. A thank-you email was sent.',
    link: '/demo/orders/order-003',
    is_read: true,
    created_at: '2026-03-15T10:00:00Z',
  },
]

// Computed stats
export const DEMO_STATS = {
  totalRevenue: DEMO_ORDERS.filter(o => o.payment_status === 'paid').reduce((acc, o) => acc + o.amount, 0),
  activeOrders: DEMO_ORDERS.filter(o => o.order_status === 'new' || o.order_status === 'in_progress').length,
  completedOrders: DEMO_ORDERS.filter(o => o.order_status === 'completed').length,
  profileViews: 247,
}
